[project]
name = "sagemaker-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.11"
dependencies = [
    "ipykernel>=6.30.1",
    "sagemaker>=2.251.1",
]
